events {}

http {
	include /etc/nginx/mime.types;	# Tarayıcıya gönderilen dosyaların türlerini (css, js, html, png vb.) doğru tanımasını sağlar. Yoksa web sitendeki tasarımlar bozuk görünebilir.
    default_type application/octet-stream;	# Eğer dosya türü bilinmiyorsa, tarayıcıya "bu indirilebilir bir dosya" demesini sağlar.

	server {
		listen 443 ssl;
		server_name atursun.42.fr;

		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;

		ssl_certificate /etc/ssl/certs/cert.pem;
		ssl_certificate_key /etc/ssl/private/key.pem;

		root /var/www/html;
		index index.php;	# Siteye girildiğinde otomatik açılacak ilk dosya, WordPress'in ana dosyası bu olduğundan ilk bunu arayacak.

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		    fastcgi_param PATH_INFO $fastcgi_path_info;
		}

		# reverse proxy
		# Birisi tarayıcıda https://atursun.42.fr/static-website yazarsa, Nginx arka planda bu isteği alır ve ağdaki static-website konteynerinin 80 portuna gönderir.
		location ^~ /static-website {
			proxy_pass http://static-website:80/;
    	}
		location ^~ /adminer {
			proxy_pass http://adminer:85/;
    	}
	}
}
