events {}

http {
	include /etc/nginx/mime.types;
    default_type application/octet-stream;

	server {
		listen 443 ssl;
		server_name atursun.42.fr;

		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;

		ssl_certificate /etc/ssl/certs/cert.pem;
		ssl_certificate_key /etc/ssl/private/key.pem;

		root /var/www/html;
		index index.php;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		    fastcgi_param PATH_INFO $fastcgi_path_info;
		}

		location ^~ /static-website {
			proxy_pass http://static-website:80/;
    	}
		location ^~ /adminer {
			proxy_pass http://adminer:85/;
    	}
	}
}
