events {}

http {
server {
        listen 84;
        server_name atursun.42.fr;

     	root /var/www/html;
        index index.html;

        location / {
                try_files $uri $uri/ =404;
        }
}

}
