services:
  mariadb:
    build: ./requirements/mariadb   # Dizindeki dockerfile'dan image build ediyorsun
    container_name: mariadb
    restart: always
    networks:
      - inception
    expose:                       # Sadece internal erişim. dışarıdan erişmezsin.
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb       # DB önce başlayacak demek. 
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html   # wordpress servisinin Aynı volume, Nginx WordPress dosyalarını okuyabilir

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  mariadb:





# expose → sadece container içi
# ports → dış dünyaya açık