[mysqld]
# Varsayılan olarak MariaDB sadece localhost'u (kendi konteyner içini, 127.0.0.1) dinler. 0.0.0.0 yaparak MariaDB'ye "Docker ağındaki diğer konteynerlerden (örneğin WordPress ve Adminer) gelen bağlantıları da kabul et" emrini veriyoruz. Bu olmazsa WordPress veritabanına bağlanamaz.
bind-address    = 0.0.0.0
socket          = /run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
port            = 3306